import './globals.css'
import { Inter } from 'next/font/google'
import ReduxProvider from '@/app/store/provider'
import { ProvidersReactQuery } from './providersReactQuery'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ProvidersReactQuery>
          <ReduxProvider>
            {children}
          </ReduxProvider>
        </ProvidersReactQuery>
      </body>
    </html>
  )
}
